# Generated by Django 3.0 on 2020-06-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=90)),
                ('local_address', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment_All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=90)),
                ('local_address', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/media/item_default.png', upload_to='media/test')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='default.', upload_to='media/Profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Rent',
            fields=[
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=256)),
                ('addhar_id', models.IntegerField()),
                ('residence_address', models.CharField(default='kuch nhi', max_length=256)),
                ('profession', models.CharField(default='Student', max_length=20)),
                ('voter_id', models.IntegerField()),
                ('image', models.ImageField(default='default.png', upload_to='media/rent')),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Rented', 'Rented')], default='Rent', max_length=10)),
                ('price', models.CharField(default='100', max_length=100000000)),
                ('property_type', models.CharField(default='1BHK', max_length=10)),
                ('property_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('on_rent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Buy',
            fields=[
                ('email', models.EmailField(default=False, max_length=256)),
                ('moblie', models.CharField(default=False, max_length=10)),
                ('status', models.CharField(choices=[('Sale', 'Sale'), ('Buy', 'Buy')], default='Sale', max_length=10)),
                ('property_image', models.ImageField(default='default.png', upload_to='media/user_booked')),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(default='1BHK', max_length=19)),
                ('property_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('on_buy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('O', 'Rented')], max_length=8)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.FloatField()),
                ('squarefoot', models.FloatField(default=100.0)),
                ('city', models.CharField(max_length=100)),
                ('town_address', models.CharField(max_length=100)),
                ('bedroom', models.IntegerField(default=2)),
                ('bedroom_img', models.ImageField(upload_to='media/bedroom_img')),
                ('kitchen_img', models.ImageField(upload_to='media/kichen_img')),
                ('let_bath', models.IntegerField(default=2)),
                ('swimming_pool', models.ImageField(default='/media/default/item_default.png', upload_to='media/swim_pool')),
                ('property_structure', models.ImageField(default='default.png', upload_to='media/proerty_structure')),
                ('property_type', models.CharField(default='1BHK', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
